const GET_CATLOG_ITEMS = 'GET_CATLOG_ITEMS';
const CREATE_CATALOG_INSTANCE = 'CREATE_CATALOG_INSTANCE';
const SHOW_CREATE_INSTANCE = 'SHOW_CREATE_INSTANCE';
const HIDE_CREATE_INSTANCE = 'HIDE_CREATE_INSTANCE';
const SHOW_CREATE_DIALOG = 'SHOW_CREATE_DIALOG';
const HIDE_CREATE_DIALOG = 'HIDE_CREATE_DIALOG';
const SET_CREATE_WIZARD_STEP_VALID = 'SET_CREATE_WIZARD_STEP_VALID';
const NAVIGATE_REQUEST = 'NAVIGATE_REQUEST';
const NAVIGATE_REQUEST_CLEAR = 'NAVIGATE_REQUEST_CLEAR';

export {
  GET_CATLOG_ITEMS,
  CREATE_CATALOG_INSTANCE,
  SHOW_CREATE_INSTANCE,
  HIDE_CREATE_INSTANCE,
  SHOW_CREATE_DIALOG,
  HIDE_CREATE_DIALOG,
  SET_CREATE_WIZARD_STEP_VALID,
  NAVIGATE_REQUEST,
  NAVIGATE_REQUEST_CLEAR
};
