const GET_CATLOG_ITEMS = 'GET_CATLOG_ITEMS';
const CREATE_CATALOG_INSTANCE = 'CREATE_CATALOG_INSTANCE';
const SHOW_CREATE_INSTANCE = 'SHOW_CREATE_INSTANCE';
const HIDE_CREATE_INSTANCE = 'HIDE_CREATE_INSTANCE';

export {
  GET_CATLOG_ITEMS,
  CREATE_CATALOG_INSTANCE,
  SHOW_CREATE_INSTANCE,
  HIDE_CREATE_INSTANCE
};
